version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    networks: [postgres]
    ports: ["5432:5432"]
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    env_file: [".env"]
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
  cheeseria-api:
    depends_on: [postgres]
    networks: [postgres]
    ports: ["3000:3000"]
    env_file: [".env"]
    build:
      context: .

networks:
  postgres:
    driver: bridge
